### ISSUE TITLE
Dispatch uploaded patient data from CSV- load patient data into app DB

### ISSUE THREAD

**Issue by pete-gov** [CDCgov/prime-central#100]
In #54 we created basic functionality to screen and process a patient CSV file. This is loaded into an object and displayed for review. One the upload is confirmed, this data needs to be loaded into the data store for the application (which is currently incomplete).

Reference:

https://github.com/CDCgov/prime-data-input-client/blob/main/frontend/src/app/patients/ManagePatients.jsx
* Good rows are kept in the `jsonImport.data` object
* These are sent to `CSVModalForm.jsx` in the `CSVModalForm` function via the `data` object

https://github.com/CDCgov/prime-data-input-client/blob/main/frontend/src/app/patients/CSVModalForm.jsx
* On confirmation, good data exists in the `data.data` object
* The `Confirm Import` buttons currently have empty on-click functions, this is where the function needs to be built to add data into the data store

**Comment by pete-gov** [comment]
Depends on #90 and associated implementation tickets. Related to #46 as these two tickets will likely use the same dispatch code.

**Comment by willusds** [comment]
Prioritize for AFTER the backend is built to figure out the best approach for this

**Comment by willusds** [comment]
Did this a different way, patient upload implemented in api
