### ISSUE TITLE
Dispatch test queue updates

### ISSUE THREAD

**Issue by pete-gov** [CDCgov/prime-central#101]
In #53 we created functionality to add patients to a test queue, currently implemented in localstorage. 

Once the backend in #90 is implemented, we will need to add functionality to dispatch this information from localstorage to the backend database.

**Comment by aliciabeckett-gov** [comment]
Is this story- Save test queue to the cloud (like not just in the browser)?

**Comment by pete-gov** [comment]
This one is a technical task, I don't think it needs a story. It's an output from the story in #53. (but your summary is accurate!)

**Comment by willusds** [comment]
Moving to 4 with the epic

**Comment by willusds** [comment]
Already covered!
