### ISSUE TITLE
Develop Legal Paperwork for Onboarding a Partner

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-central#103]
**Describe your feature request in this format: As a __(persona)___ I want to ___(action or feature)__ so that ___(expected outcome)__**
A clear and concise description of what the problem, user persona, and expected outcome.

**Describe the solution you'd like and the specific acceptance criteria to be completed**

- [ ] Terms of Use
- [x] ATO
- [x] PIA

**Describe alternatives you've considered**

**Additional context**

**Comment by willusds** [comment]
CDC helping lead on this

**Comment by aliciabeckett-gov** [comment]
Draft PIA is completed

**Comment by aliciabeckett-gov** [comment]
ATO Date                           11/23/2020
ATO Expires                       03/30/2021

**Comment by willusds** [comment]
Done! https://simplereport.cdc.gov/terms-of-service/
