### ISSUE TITLE
Develop Marketing Materials for the App to recruit Pilot Partner Sites

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-central#108]
Had a conversation with @cygov and @sparkle-usds about the requests we've been getting for demos and information about the app, and what we will need going forward. The output of that meeting is we should:

- [ ] Create a video that demos the app to share with potential partners/pilot sites @cygov @hmyers-cms 
- [ ] Get the video cleared by CDC to share

- [x] Develop a 1 pager about the app to share with potential partners/pilot sites @cygov @aliciabeckett-gov 
- [x] Get the 1 pager cleared by CDC to share

- [x] Develop a plan for how we will onboard pilot sites to the community @sparkle-usds 

Website

- [x] Develop content for the website.
- [x] Develop a way for testing site to "sign up" and register to use the App.
- [x] Get the website content cleared by CDC

**Comment by aliciabeckett-gov** [comment]
@cygov is the video still happening?

**Comment by aliciabeckett-gov** [comment]
Editing this ticket to reflect the work that needs to be done for the website.

**Comment by cygov** [comment]
Now that we have a first draft of messages being reviewed, we'll move forward with recording a demo!

**Comment by aliciabeckett-gov** [comment]
Video is blocked until we have a prod ready demo site to do it on.

**Comment by willusds** [comment]
Plan for onboarding sites is in progress (and iterating as we scale) the demo video is in the works. We've started posting our demo videos publicly and sharing them widely with partners (and will soon add them to the sites): https://www.youtube.com/playlist?list=PL3U3nqqPGhaZbRpj1r7dE1W2tIzcjthbh
