### ISSUE TITLE
[closed as dupe] ~Accept CSV file to populate patient records~

### ISSUE THREAD

**Issue by pete-gov** [CDCgov/prime-central#11]
As an **Organization Administrator** I will need to use a _CSV export from my Organization's System of Record_ to **populate patient data.** 

**Request 1**

As **engineers** building this capability, we will need to _define a simple structure this type of CSV_ that we can **use for prototyping**.

Define an initial prototype CSV structure that includes:

* Unique ID
* First/Last Name
* Address
* Date of Birth
* Phone Number

**Other data fields necessary for prototype??**

**Request 2**

Make a decision about how this CSV will be handled, either client side or via upload. Build the resulting thing (probably separate issues).

Ref: https://usds.slack.com/archives/C01C5EABU91/p1602087854009400

**Request 3**

Build the thing server side that will accept the information and put it into a database.

**Request 3**

Add use case handling including:

1. de-duplicating data in a CSV
2. handling errors in a CSV

**Comment by pete-gov** [comment]
Based on the API specification Shelby created initially for TestRegistration here: https://github.com/CDCgov/prime-data-input-api/blob/master/openapi.yml

Looks like we're starting with:

    TestRegistration:
      type: object
      required:
        - id
        - test_datetime
        - first_name
        - last_name
        - phone
        - birth_date
      properties:
        id:
          type: integer
          format: int64
        test_datetime:
          type: string
          format: date-time
        first_name:
          type: string
        middle_name:
          type: string
        last_name:
          type: string
        birth_date:
          type: string
        phone:
          type: string
        email:
          type: string
        address:
          type: string
        city:
          type: string
        state:
          type: string
        zipcode:
          type: string
        preferred_contact_method:
          type: string
        race:
          type: string
        ethnicity:
          type: string
        sex:
          type: string
        symptoms:
          type: array
          items:
            type: string

**Comment by pete-usds** [comment]
For CSV processing unit testing, I'm thinking we'll need at least the following variants of row data:

1. Good rows
2. One row missing each unique column
3. One row missing multiple unique columns
4. One row with extra columns
5. One CSV with extra columns 
6. One CSV missing columns
7. Rows with invalid column data (i.e. invalid email addresses?)
8. Empty CSV (column headers only)
9. CSV with duplicate data
10. CSV with updates/changes to data in rows with the same ID as a previous CSV

hrm hrm. Will need to think through a cleaner way to do this than by just having a bunch of CSVs lying around.

**Comment by pete-gov** [comment]
Modified this a bit per this conversation: https://usds.slack.com/archives/C01C5EABU91/p1602174735044700?thread_ts=1602167860.042000&cid=C01C5EABU91

**Comment by pete-gov** [comment]
Closing this as a duplicate of #54
