### ISSUE TITLE
Get information about sites and their device usage (make sure it works with our app)

### ISSUE THREAD

**Issue by willusds** [CDCgov/prime-central#110]
Based on the suggestion in #64: would be handy at some point to have a specific list of devices and operating systems that people will expect to use on the pilot side (i.e. “iPad mini 3 / iOS 12”)

**Comment by aliciabeckett-gov** [comment]
@aliciabeckett-gov follow up with Zach on first pilot site's device

**Comment by aliciabeckett-gov** [comment]
From our first site:

_"We have both laptops and iPads but the testing staff would most likely only use laptops. 
 
Chrome and Internet Explorer are both available on all laptops."_
