### ISSUE TITLE
Create content for unauthenticated homepage

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-central#111]
Create content for unauthenticated homepage. This content should allow users to learn more about the app.

- [x] Develop Content for the website
- [x] Clear the design/content with CDC

Content
- [x] About the app
- [x] How to sign up
- [x] Screenshot of the app

Note: the content development work for this has been handed off to the contracted team.

**Comment by katiealoisi** [comment]
@cygov Let me know if you want to meet to discuss the audience and what might be helpful for them. We can go through the [FAQs](https://docs.google.com/document/d/1DTi8JkG27WJtpw-nGZ2CUAWgaY50bNSPM6eYJ72SRPA/edit) as well. By the way, I wasn't able to view them but requested access!

**Comment by sharmaneil** [comment]
Ideas for additional content:
- link to any training documentation, product screenshots, or short, video demos
- contact us, specifically messaging around "if you run into a bug, please reach out to XXX with a description". Pretty sure we won't have great log/test coverage

**Comment by willusds** [comment]
Done!
