### ISSUE TITLE
Develop frontend updates to Settings Page (Facility Address, Facility Phone)

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-central#118]
Engineering work to add fields
- [ ] Facility Address
- [ ] Facility Phone

See mockup below 
<img width="1010" alt="Screen Shot 2020-12-02 at 8 26 09 AM" src="https://user-images.githubusercontent.com/50637336/100894000-38966680-3479-11eb-85cc-d1b3efb6f6f5.png">

**Comment by willusds** [comment]
@aliciabeckett-gov has the list of potential options and the logic for how the selection works

**Comment by aliciabeckett-gov** [comment]
The facility Address and Facility Phone are not blocked by swab designs. I'm removing the blocked tag so someone can start on those while we wait for the swab designs.

**Comment by aliciabeckett-gov** [comment]
Here's a mock to use for the facility address and phone fields

<img width="1010" alt="Screen Shot 2020-12-02 at 8 26 09 AM" src="https://user-images.githubusercontent.com/50637336/100893430-9b3b3280-3478-11eb-8447-5f07d204d715.png">

**Comment by aliciabeckett-gov** [comment]
Mockup to use for Facility Address and Phone

<img width="1010" alt="Screen Shot 2020-12-02 at 8 26 09 AM" src="https://user-images.githubusercontent.com/50637336/100893623-cc1b6780-3478-11eb-947c-453bdfe3051b.png">

**Comment by timbest-cdc** [comment]
adding mock to allow multiple facilities https://www.figma.com/proto/VGBQmqKMTjO1tdYTCpzwcd/SimpleReport?node-id=166%3A2311&scaling=scale-down

**Comment by benwarfield-usds** [comment]
As far as I know we are not allowing multi-select facilities in the initial facility release, correct?

**Comment by timbest-cdc** [comment]
Not sure what the initial release is. I think it makes sense to push the backend incrementally. First untangle the current facility for org. But our immediate goal and number 1 priority is to add a second (and third) facility to the app.
