### ISSUE TITLE
Add a timer to testing cards

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-central#121]
- [x] Design
- [x] Validate design with users

- [ ] Code

**Default view:**
<img width="1015" alt="Screen Shot 2020-12-03 at 3 01 09 PM" src="https://user-images.githubusercontent.com/60664222/101081704-6d3d1780-3578-11eb-8fb3-686484bd5a30.png">

**Timer running:**
- Clicking the timer while it is running should stop the timer and reset it to the default view
<img width="1018" alt="Screen Shot 2020-12-03 at 3 04 25 PM" src="https://user-images.githubusercontent.com/60664222/101082073-e5a3d880-3578-11eb-817b-96022efe0425.png">

**Timer completed:**
- When the timer is complete, it should play this noise: https://freesound.org/people/andersmmg/sounds/511491/
- The time elapsed should begin counting up from 15 minutes
- Clicking the reset icon after it is completed should return the timer to the default view
<img width="1017" alt="Screen Shot 2020-12-03 at 3 04 35 PM" src="https://user-images.githubusercontent.com/60664222/101082080-e9375f80-3578-11eb-9e89-394067be5f78.png">

**Comment by willusds** [comment]
@hmyers-cms to work on updating and adding mocks here for start/stop timer

**Comment by willusds** [comment]
Design is done, @aliciabeckett-gov is validating with users, will update as it gets validated

**Comment by hmyers-cms** [comment]
This ticket is ready for engineering

**Comment by dmethvin-gov** [comment]
@hmyers-cms a few questions before I get started:
* Where do we get the starting time? The ticket uses 15 minutes but does that vary with different test devices?
* Is the black background shown in the "Timer running" shot a picture of it running? Or is that timer stopped? What is the visual difference between a running timer and a stopped timer? Is that semicircle arrow supposed to spin or animate while the timer runs?
* _"Clicking the timer while it's running should stop the timer."_ When it "resets to the default view" does that mean the timer itself resets to 15 minutes?
* _"Clicking the reset icon..."_ is that the little semicircle arrow? Is the click target area only the arrow, or is it the entire group of things there including the text?

**Comment by dmethvin-gov** [comment]
* Should we allow them to submit a result before the timer goes off? The pics show the submit button active.
* If the timer has reached 15 minutes can the user just submit a result to dismiss the timer?
* Do we just play the sound once, or should we repeat on some interval as long as a test is ready? It's a pretty subtle sound so I could see someone missing it.

**Comment by hmyers-cms** [comment]
- It should always be 15 minutes for right now. At some point we may need the ability to have the time connected to the device type but for now just 15 mins always
- The black background is actually navy blue (the same color used to indicate the active page in the nav), and it is a shot of it running. There is no paused timer. Clicking it just resets it to the default (15 mins)
- Yes, the reset icon is the semicircle arrow, and the hit target on the finished result should just be the icon
- Yes we should allow results to be submitted before the timer goes off—the timer is not a requirement (they may use one on their phone instead)
- II don't know what you mean when you ask about dismissing the timer
- The sound plays only once. 

See the desired interaction in action in the prototype (realized this wasn't working before but is fixed now): https://www.figma.com/proto/CEzBM8kUw8LyWdfAhUThYb/Engineering-Ready-Prototype?node-id=47%3A5&scaling=scale-down

**Comment by dmethvin-gov** [comment]
> I don't know what you mean when you ask about dismissing the timer

If the timer is counting up from 15:00, do they need to stop the timer or can they just submit a result with the timer still running? I assume the former.

**Comment by hmyers-cms** [comment]
Yes, they can submit any time

**Comment by dmethvin-gov** [comment]
Sorry I ask so many questions, but a feature like this is much more than just a few things on the screen.

* If the user is elsewhere in the app when a timer goes off, not on the queue tab, should it still play the sound? It seems like this needs to be a global thing that happens regardless of where they are (editing a patient record, entering ask-on-entry questions, reviewing test history, etc.) 
* Should there be any indication other than the sound when they're on a different page and a timer goes off? Just wondering whether they might miss a timer because they're editing a patient record or something. On Chrome and Firefox there's a little speaker icon that appears on the tab as a hint it made a sound so maybe that's enough.

**Comment by hmyers-cms** [comment]
- Yes, it should continue the count and play the sound regardless of which page of the app you are in

- You raise a good question about about some other indication. I think for now just the sound is enough. But this is something we should keep an eye on as users actually start using the feature
