### ISSUE TITLE
[closed as dupe] ~Define Data Input Data Storage Schema (Patient Data)~

### ISSUE THREAD

**Issue by pete-gov** [CDCgov/prime-central#13]
With multiple folks collaborating on API services, web forms, and infrastructure, we need to define an initial data schema for patient data that everyone can work with. 

Ideally software defined and compatible across these workstreams. Reference Issue #11 for CSV structure.

Initially, this storage schema should include at least:

1. Fields from CSV in #11 
2. Creation time
3. Last modified time
4. Array style queue fields for each time in queue - status, time added to queue, time out of queue (how to track order in queue?)
5. Array style test fields for each test - test time, testing device type, testing device id, testing results, symptomatic?

**Acceptance Criteria / Outputs:** 
- Machine readable schema

**Comment by pete-gov** [comment]
From an API perspective, many of these fields are now "documented in code" in the API specification:

https://github.com/CDCgov/prime-data-input-api/blob/master/openapi.yml

**Comment by aliciabeckett-gov** [comment]
It's going to be important that this data is editable. Not sure if that's going to impact the data model, but keeping track of edits/updates is going to be important.

**Comment by aliciabeckett-gov** [comment]
UI is here: https://heather574841.invisionapp.com/console/PDI-10-14-2020-HM-ckg9uf825007z01yg6dgr93w1/ckg9uf8v40077010i9ovger5g/play

**Comment by pete-gov** [comment]
This stuff is duplicated out in various other tickets, including #41 #39 #54 #55 - especially since we're re-ordering those things and having "data structure" be an output of features as we go-fast, makes sense to close this one out.
