### ISSUE TITLE
Develop user profile

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-central#135]
As a user, I want to be able to view my profile information and log out.

The profile information will be available via a dropdown widget and should include:
- [x] First and last name
- [ ] Log out capability

Discussion on this topic in Slack: https://usds.slack.com/archives/C019PRYMR0Q/p1605638797142600

**Comment by hmyers-cms** [comment]
<img width="364" alt="Screen Shot 2020-11-17 at 2 21 20 PM" src="https://user-images.githubusercontent.com/60664222/99437350-5774f480-28e0-11eb-80f3-2c38c26a44a3.png">

**Comment by TomNUSDS** [comment]
Think this layout approach depend on mouseover hovers? 

These will be problematic when we eventually support tablets.

**Comment by katiealoisi** [comment]
We were thinking the drop-down should be triggered on click (on tap for tablets). Do you think see any issues with that approach?

**Comment by willusds** [comment]
Dependent on log-in info, can be hardwired in for fallback, need an API call

**Comment by katiealoisi** [comment]
Updated mocks, per convo during sprint planning. In order, the drop-down should show the user's first and last name, email address, organization name (NOT facility), and ability to log out.
<img width="561" alt="userprofile" src="https://user-images.githubusercontent.com/66079940/100777309-a425f880-33d3-11eb-9e0e-70da1881c5b5.png">

**Comment by timbest-cdc** [comment]
see https://github.com/CDCgov/prime-data-input-client/pull/216#issuecomment-738802429 for feedback

**Comment by TomNUSDS** [comment]
Assigning to @timothybest-usds to close once the logout url is working on the server.

**Comment by timbest-cdc** [comment]
Logout link implemented here: https://github.com/CDCgov/prime-data-input-client/pull/233
future design clean up captured in https://github.com/CDCgov/prime-central/issues/171
