### ISSUE TITLE
Define user journey for onboarding process

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-central#141]

**Comment by katiealoisi** [comment]
Hey @sparkle-usds! Alicia asked @hmyers-cms and I to sync w/ you to define the user journey for the onboarding process. How can we help out? If you have an existing ticket on this, please point us to it.

**Comment by sparkle-usds** [comment]
@katiealoisi or @hmyers-cms, no existing ticket. Feel free to put some time on my calendar and we can talk through this.

**Comment by katiealoisi** [comment]
Closing this ticket per Slack convo with Sparkle and Heather.

**Comment by katiealoisi** [comment]
Closing this ticket per Slack convo with Sparkle and Heather.
