### ISSUE TITLE
Frontend: Support relative paths site wide

### ISSUE THREAD

**Issue by pete-gov** [CDCgov/prime-central#143]
To deploy using URL path routing, the entire app will need to be able to run out of any root directory (such as `/app/`). It is currently wired up with what appears to be a number of absolute links in various files which prevents it from running in a relative root.

**Acceptance Requirements:**

Verify site can be deployed and run entirely from any subdirectory (such as `/dev/test/app`)

**Comment by pete-gov** [comment]
Easiest way to test this in Azure:

1. Set up Azure CLI if you don't have it set up yet.
2. Run `npm run deploy-azure-dev`
3. See if this works: https://cdc.simplereport.org/dev/app
4. Run `npm run deploy-azure-prod`
5. See if this works: https://cdc.simplereort.org/app

**Comment by nickrobison-usds** [comment]
I'll give this one a shot, and when I fail, I pass it along!

**Comment by pete-gov** [comment]
This was fixed by adding some environment variables to the package.json for the build scripts.
