### ISSUE TITLE
Need a new Demo/Training Environment

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-central#150]
We need an environment that mirrors production that can be used for demos and training. It needs to be relatively stable, can have authentication (or not), and does not have any real user data.

Bonus points if it comes seeded with some default people and settings, but that's not required.

**Comment by pete-gov** [comment]
Can you clarify what "mirrors production" means? Just a system running the same version as production, right? (generally we wouldn't want to spin up full production level stacks for demos/training)

**Comment by aliciabeckett-gov** [comment]
Yes, running the same version

Sent from my iPhone

On Nov 30, 2020, at 6:28 AM, Peter Waterman <notifications@github.com> wrote:

﻿

Can you clarify what "mirrors production" means? Just a system running the same version as production, right? (generally we wouldn't want to spin up full production level stacks for demos/training)

**Comment by pete-gov** [comment]
https://demo.simplereport.org / deployed in similar configuration to beta.
