### ISSUE TITLE
Design updates to the Settings Page (Facility Addres, Facility Phone, Swab Type)

### ISSUE THREAD

**Issue by willusds** [CDCgov/prime-central#152]
The Global Settings page needs to include 3 additional fields:
-Facility & Testing Lab Address
-Facility Phone Number
-Swab Type

- [ ] Design needs to be updated @hmyers-cms

**Comment by willusds** [comment]
Once completed #153 and #118 can begin

**Comment by katiealoisi** [comment]
Hold off on design front. Wait for guidance on what exactly is required.

**Comment by willusds** [comment]
Closing because it needed swab type, and now with #106 can close
