### ISSUE TITLE
When you change a CLIA number you can't save the settings page

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-central#161]
Changing the CLIA number on the settings page prevents saving.

**Impact**
Please describe the impact this bug is causing to your program or organization.

**To Reproduce**
1. Go to settings page
2. Edit the CLIA number
3. Press Save
4. Nothing happens. If you refresh the page the save didn't happen.

**Expected behavior**

**Screenshots**

**Logs**
If applicable, please attach logs to help describe your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by timbest-cdc** [comment]
The settings page was rewritten in https://github.com/CDCgov/prime-data-input-client/commit/07b881049dc83ef45c87a5ba18c6c5fd5a52f4d2 and saving the facility CLIA number is working
