### ISSUE TITLE
Define our user groups, pilot partner, research partner, vendors, etc.

### ISSUE THREAD

**Issue by willusds** [CDCgov/prime-central#32]
Lead: Drew

**In-progress Mural board**
https://app.mural.co/invitation/mural/primedatainput6410/1601833898368?sender=ud6a3555dd1821b626a2b3726&key=24438ceb-5133-42e7-8937-a40e547b5050

**Partners**

_Pilot partners_ are jurisdictional public health departments we are actively working with to develop software product(s). Observations, input, and feedback from research and testing will contribute directly to what we build.

_Research partners_ are jurisdictional public health departments we are engaged with in a learning capacity. Observations, input, and feedback from research and testing will inform and influence what we are building with our Pilot partners. 

**Users**

- Public health departments (state, county) [Data Input, Data Hub]
  - Public health leadership, public health employees, vendors and contractors
    - Testing locations: people actively working in day-to-day operations, people having tests administered [Data Input]
      - Mobile
      - Non-traditional
      - etc
    - "HQ": people ingesting or receiving files, quality checking or cleaning files, transforming data and taking action, or conducting analysis and reporting [Data Hub]
      - Epi 
      - Data Analyst
      - IT
- Hospitals [Data Automation]
  - Hospital leadership, hospital employees, vendors and contractors
    - Lab staff
    - IT
    - ???

**To do**

- [ ] Add to our published docs
- [ ] Follow up with Tom S, who originally surfaced this

**Comment by katiealoisi** [comment]
Gathering my thoughts on data automation stakeholders prior to our 10am meeting: 

**Data Automation End Users (users of the automation solution)** 

- Hospital employees collecting and reporting data for the COVID-19 response
- Lab employees collecting and reporting data for the COVID-19 response
- State public health employees using this data and reporting it to the federal government

**Data Automation Vendors (providers/enablers of the automation solution)**

- EMR / ERP Vendors (Epic, Cerner, AllScripts, Meditech)
- Third Party Integrators (Juvare/EMResource, Cloverleaf, Appriss, National Response Portal, UI Path, Vizient, Smartsheet)

_Caveat for Data Automation "pilot partners"_: The term "pilot" is used more broadly for Data Automation vs. the other PRIME projects. At the state level, a pilot partner is a state we are partnering with to pilot automation solutions within their state. At the hospital level, a pilot partner is a hospital or health system we are partnering with to pilot an automation solution (not necessarily in a pilot state).

**Comment by jlusds** [comment]
Data Hub End users
- Data analysts receiving, formatting, manipulating, editing lab report files and uploading into systems
- Epidemiologists who perform actions based on data, such as contact tracing (everyday health actions) and analysis and reporting

Enablers/Stakeholders
- Testing labs administrators who collect information at point of care, create flat files
- Testing lab IT team who build/sign off on integration systems and workflows 
- Public Health IT team who build/sign off on systems and workflows
- Public Health leadership

**Comment by willusds** [comment]
@drew-usds Is this pretty much done at this level? Each team has kind of started working on this independently, so I think we can close it?

**Comment by willusds** [comment]
Considering this closed!
