### ISSUE TITLE
Set up domain: https://cdc.gov/prime

### ISSUE THREAD

**Issue by willusds** [CDCgov/prime-central#33]

**Comment by benwarfield-usds** [comment]
CDC WCMS has done this already, we just have to get clearance to publish.

**Comment by drew-usds** [comment]
**Test URLs**


  | Admin Url | DEV Target URL | LINK Target URL
-- | -- | -- | --
Staging (sandbox) | https://wcms-wp-stage.cdc.gov/prime/wp-admin/ | https://wwwdevstg.cdc.gov/prime/ | https://wwwlinkstg.cdc.gov/prime/index.html
Production | https://wcms-wp.cdc.gov/prime/ | https://wwwdev.cdc.gov/prime/ | https://wwwlink.cdc.gov/prime/ (internal)https://www.cdc.gov/prime/ (external)

**Intranet documentation**
https://webinfo.cdc.gov/display/DTT/PRIME+Site
