### ISSUE TITLE
Introduce CI/CD for cloud.gov deploys for Data-Input Repos

### ISSUE THREAD

**Issue by sharmaneil** [CDCgov/prime-central#38]
Probably would use Github actions.

Some comments (mostly from Ben) here:
https://usds.slack.com/archives/C01C5EABU91/p1602096068022400

Repos:
- https://github.com/CDCgov/prime-data-input-api
- https://github.com/CDCgov/prime-data-input-client

Tasks:

- [x] branch tests for client that run when needed
- [x] deploy job for client prototype
- [ ] automatic deployment on agreed-upon intervals or upon merge to `main`

**Comment by pete-gov** [comment]
I think @benwarfield-usds has been working on this - I've seen a couple updates in slack. https://usds.slack.com/archives/C01B2LH9B3P/p1602627088010200

**Comment by benwarfield-usds** [comment]
Deferring automatic deployment from `main`, and closing this.
