### ISSUE TITLE
Add user roles and access control

### ISSUE THREAD

**Issue by pete-gov** [CDCgov/prime-central#40]
As an administrator of a testing site, I want to limit who can change settings and see personal information, so that I am following HIPAA best practices and protecting myself from untrusted users.

Design is in ticket #133 

- [ ] Add user roles in the admin UI
- [ ] Assign users roles and know what role a user has when they are logged in
- [ ] Limit access to functionality and UI based on a user's role

**Comment by willusds** [comment]
Broken into different tickets and for future sprints (8 focuses on ac)
