### ISSUE TITLE
Incorporate Ask on Order Entry (AOE) Questions into MVP

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-central#41]
Alicia and I met with Alex Ganim to walk through the mock ups. **From a CDC optics perspective, it is very important that the MVP include the federally-required data fields** (she is going to send me a file with those data fields and I will drop it here). Some of these fields are things that don't change (e.g. race) and some of them do change (e.g. pregnant/not pregnant, symptoms). Based on research, nursing homes we spoke w/ do not currently collect this information from their staff at all, so when we include these fields, they should be optional.

**Our feedback**: These fields are important but they may not be a v1 feature. Alex suggested that if these are not part of v1, we need to at least acknowledge these fields and have an answer on when they will be included (which should be soon after, like v2). 

**Compromises** we discussed if this is not included in v1, starting with the most preferred from CDC perspective: 

- Include these data elements for real in v2, but grayed out / as a placeholder in v1
- Design a workflow for collecting these data elements (mock ups only) to demonstrate momentum/commitment to adding them in v2

**My open questions:**
- This could be achieved a couple of ways (below). Which one is more feasible from an engineering perspective for v2? Which one is more user-friendly (for patients and administrators)?
  - Pre-test survey (like we designed previously in the mock ups)
  - In-person collection by test administrator at time of test
  - Any other ideas?

**Comment by pete-gov** [comment]
This page from a research team in Rhode Island is likely a good starting point: https://thepolicylab.github.io/covid-forms/data-standard.html 

Also they've already put a bunch of that stuff into use on pages in the repo, for example: https://thepolicylab.github.io/covid-forms/complete-registration.html

**Comment by katiealoisi** [comment]
Materials from Alex about the reporting requirements below! 

Guidance: https://www.hhs.gov/answers/is-additional-information-including-technical-specifications-available-to-support-laboratories-with-implementation/index.html

Reporting requirement specifications: https://www.hhs.gov/sites/default/files/hhs-guidance-implementation.pdf

https://www.hhs.gov/sites/default/files/non-lab-based-covid19-test-reporting.pdf

 Flat CSV File – housed on APHL’s website, row 7: https://app.smartsheet.com/b/publish?EQBCT=fab9882490c0481d924bf8e728be757e

**Comment by aliciabeckett-gov** [comment]
@katiealoisi should this get closed or is there more work to do here?

**Comment by aliciabeckett-gov** [comment]
This seems like a dupe with #56.  I suggest we close this ticket.

**Comment by willusds** [comment]
Sounds good!
