### ISSUE TITLE
Add New Person/Edit Person in App UI

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-central#46]
As a test administrator I want to add one new patient so that I can easily test them without doing a new CSV upload.

Description: Build the Web Page and associated API request to add one patient through the Web App UI. These are in the mock ups. All of the required HHS fields will need to be added.

See airtable here for field details: https://airtable.com/invite/l?inviteId=invRZoEMgd5O1ppty&inviteToken=4eba912ce77015c2062681c5c8f36b6951750981b49124a130a46a20fe3ac5aa

**Comment by pete-gov** [comment]
@sharmaneil first pass of example JSON schema for adding a patient is the patient.schema.json file in this PR: https://github.com/CDCgov/prime-data-input-client/pull/7

**Comment by sharmaneil** [comment]
@aliciabeckett-gov is this MVP-required? It's in the backlog, but I'm tempted to get started on it

**Comment by aliciabeckett-gov** [comment]
It's not required for getting real test results recorded. So in that sense it's less important than other tickets, but we're gonna need it before we can scale.

**Comment by aliciabeckett-gov** [comment]
@hmyers-cms - is the mock up ready for engineering or do you want to make more changes? I saw the design label and wanted to check on it.

**Comment by aliciabeckett-gov** [comment]
@dmethvin-gov are you working on this now? Should we move the ticket into TODO?

**Comment by willusds** [comment]
Blocked until we have a meeting of the minds between Prime Input + Backend about indexing the fields. Can merge now until that's decided.
