### ISSUE TITLE
Search for an existing patient and add them to the test queue

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-central#53]
As someone checking in patients for a test, I want to add patients to the test queue as they arrive, so that they can be tested and their result can be recorded.

## Acceptance Criteria

As of Nov 2, 2020:

- [x] When a user searches for a patient they can search by name, ~~DOB,~~ or unique ID. (DOB removed because its untested)
- [x] Clicking the Add to Queue button will trigger the Ask on Order Entry (AOE) questions to show up on the screen.~~ (Update: this will be a separate story)
- [x] After the patient has been added to the queue show a success notification
- [x] ~~styles and animations~~ (out of scope, captured in another ticket)
- [x] unanswered question: do we want search to happen on the frontend (currently implemented), or should it make a db query? 

UI here: https://heather574841.invisionapp.com/console/PDI-10-14-2020-HM-ckg9uf825007z01yg6dgr93w1/ckg9uf8v4006w010i942z0wuo/play

**Comment by sharmaneil** [comment]
@hmyers-cms  should patients be added to the top of the queue? I believe I asked this before in an invision comment, but can't find the response from the link in the comment.

**Comment by sharmaneil** [comment]
I think this ticket is too big. Requiring the AOE questionaire means #56 becomes a blocker since the AOE form would have to exist for this ticket to be complete.

Furthermore, this ticket already requires:
- building a queue
- introducing patient search
- adding items to the queue
- removing items from the queue (presumably, otherwise the prototype would stop being functional once everyone has been added to the queue)
- alerts and other UI things

Arguably, many of the above items should be separate issues too

**Comment by sharmaneil** [comment]
This raises the question about story scope. There doesn't need to be a 1:1 mapping of pull request to stories, but this story could be a full sprint itself.

**Comment by pete-gov** [comment]
What about creating an `Epic` label and maybe a separate swim lane for epics, then linking tasks to them via # mentions? Not as clear as Jira et al, but it's a way to increase some organization in the manner that many of us are used to while sticking with github.

**Comment by switzersc-usds** [comment]
Agreed! This is more of a full workflow than a discrete user story (maybe we're all using the term a bit differently). I agree an Epic label could work to keep track of stories linked by workflow.

**Comment by aliciabeckett-gov** [comment]
@sharmaneil makes sense to move the AOE questions to a separate ticket. Do you want to break up more of the story? I saw you already started on it so don't want to disrupt your workflow on the ticket.

**Comment by hmyers-cms** [comment]
@sharmaneil to answer your question, I think newly added people should go to the bottom of the queue so that you can work through the queue chronologically from top to bottom

**Comment by sharmaneil** [comment]
I removed the AOE work from this story. Now, aside from a fair amount of style work and a few small missing things from each patient in the queue, this behemoth issue is approaching completion. 

It could use QA: https://prime-data-input-staging.app.cloud.gov/
You will have to clear browser storage. There are two ways:

1. Click the red button at the bottom of the page and then refresh the page
2. Clear it manually:
- right click
- "inspect"
- Go to the "Application" tab
- Click "Clear storage" on the left panel
- Click "Clear Site data" in the main content
- refresh the page

You can search for "Edward", "James", or "John"

**Comment by pete-gov** [comment]
Created #101 to track dispatching this data when backend is built. Closing.
