### ISSUE TITLE
add fields to CSV generator

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-central#55]
(note: this issue was misunderstood at first, but the misunderstood work was necessary so it was done in this ticket and a separate one was broken out for the originally requested work)

As a test administrator, I want a template to help me create my CSV roster of patients to upload, so that I know what format to use and will be less likely to make a mistake or have an error when the file is uploaded.

-Create CSV Template to be used in the #54 upload patients UI as a tempate
-It should have at least the fields included in the add new patient UI: https://heather574841.invisionapp.com/console/PDI-10-14-2020-HM-ckg9uf825007z01yg6dgr93w1/ckg9uf8v40077010i9ovger5g/play
-There should be data validation, and for fields that have specific values allowed the data validation should only allow those values
-The output of this ticket is an excel document

Airtable with fields needed: https://airtable.com/tblcBkHsdhAo0gbpT/viwAlMe3FeswxAMgz?blocks=hide
-CSV fields will be in the add/edit new patients

**Comment by pete-gov** [comment]
As of this writing, fields in the mockup include (bolded one are already in the CSV generator and API spec):

* **First Name**
* **Middle Name**
* **Last Name**
* **Unique ID**
* **Phone Number**
* **Email Address**
* **STreet address**
* Street address 2
* **City**
* **State**
* **Zip**
* **Race**
* **Ethnicity** 
* **Biological Sex** 
* **Birthday**

Need to add:

* County 
* Resident in congregate care/living setting
* Type of setting
* Work in healthcare
* Kind of healthcare professional

(this is a feature request on top of #42 )

**Comment by aliciabeckett-gov** [comment]
Can we please use the airtable instead of the mock up? They should be in sync but the airtable is what the mocks are based on.

https://airtable.com/tblcBkHsdhAo0gbpT/viwAlMe3FeswxAMgz?blocks=hide

As the mock ups change I'd like to keep the airtable as our source of truth.

**Comment by aliciabeckett-gov** [comment]
@pete-usds - I was imagining this ticket to be creating the file that is available for download by the test administrator. So it's the _users_ template that they download, add their patients data, and then upload to the app. So not so much the test file generator. Let me know if we should chat about this quickly.

**Comment by pete-gov** [comment]
Dropping this back to `To Do` and lower priority until #64 is resolved.

**Comment by pete-gov** [comment]
I've updated the generator with these fields by adding support for JSON Schema and deploying initial JSON schemas. There's more individual tweaking that needs to be done - such as pulling the latest schema automatically from main in prime-data-input-client (or possibly moving the tool into that repo at some point). For now I'm going to call this donesies and any further updates will be incorporated as part of testing for #54 (no need for acceptance on this due to further work being in other tickets)

PR: https://github.com/CDCgov/prime-data-input-client/pull/7
