### ISSUE TITLE
Ask on Order Entry Questions for a new Test

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-central#56]
As a provider of a COVID-19 test, I want to ask the patient the required questions, so that I am in compliance with HHS requirements, and so that public health departments have the information they need.

- [x] When a new person is added to the testing queue, ask them the questions that need to be collected at the time of test
- [x] Allow the user to complete the questions and add the patient to the queue
- [x] Allow the user to cancel out of the questions 
- [x] These questions can also be accessed from the testing queue by clicking on the "time of test questions" button on a given test
- [x] If a user tries to submit test results without completing the questions as them if they'd like to complete them before submitting.
- [x] The questions responses should be associated with a specific test for a specific patient, and may change from test to test.

UI here: https://heather574841.invisionapp.com/console/PDI-10-14-2020-HM-ckg9uf825007z01yg6dgr93w1/ckgb8i7gv00f7010a21vw0fvu/play
Airtable with required field for "time of test" here: https://airtable.com/tblcBkHsdhAo0gbpT/viwAlMe3FeswxAMgz?blocks=hide

**Comment by pete-gov** [comment]
Hey @benwarfield-usds just wanted to make sure you saw that I theoretically added a JSON schema for these questions here: https://github.com/CDCgov/prime-data-input-client/pull/7

**Comment by benwarfield-usds** [comment]
@aliciabeckett-gov should I be paying attention to the SNOMED codes, or are those just for our future reference?

**Comment by aliciabeckett-gov** [comment]
That's what will need to be passed through in the HL7 data to the health department. So it's important the answer options match the human readable text options that map to snowmed codes. But it's up to you and the other engineers to decide where the mapping to the actual snowmed codes should happen.

**Comment by benwarfield-usds** [comment]
Further questions about "Prior Test" section, tagging @hmyers-cms because there's a design question in it:

* is there a likelihood that we would want to report multiple prior tests, if we stored that information for a patient?
* what is the list of possible values for "Prior Test Type?" Is it going to be globally the same for all users, or is it possible that it would be configurable?
* if the answer to "First Test?" is "Yes", 
  * do we need to record that the question was answered in the affirmative, or can we just leave it at "there is no prior test data to record?"
  * should the subsequent inputs be disabled (or hidden) unless the answer is No?
  * do we want any kind of validation on that test date?

**Comment by aliciabeckett-gov** [comment]
is there a likelihood that we would want to report multiple prior tests, if we stored that information for a patient?
-Great question! I'm meeting with Jason Hall tomorrow and can ask him about this. Right now I think it's just the most recent prior test. What I want to find out is how the data is used at HHS/CDC so we know what they're trying to accomplish.

what is the list of possible values for "Prior Test Type?" Is it going to be globally the same for all users, or is it possible that it would be configurable?
Not configurable, these are the allowable answers for everyone:
-Molecular
-Antigen
-Antibody/Serology
-Unknown

if the answer to "First Test?" is "Yes",
do we need to record that the question was answered in the affirmative, or can we just leave it at "there is no prior test data to record?"
should the subsequent inputs be disabled (or hidden) unless the answer is No?
-If the answer is no the other inputs can be disabled
do we want any kind of validation on that test date?
-Yeah, it shouldn't be in the future or from before Feb. 1, 2020

Also, this is the HHS spec that has a lot of mappings for allowable answers for questions. I'm happy to keep answering them for you but also wanted to give the source of all my answers :)
https://www.hhs.gov/sites/default/files/non-lab-based-covid19-test-reporting.pdf

And here's the national flat file that's (part of) the spec for how these questions need to get answered so they can get coded into HL7.  The gap analysis tab is probably the most useful.
https://teams.microsoft.com/l/file/1FFE108B-9E00-4EB6-9DE0-B0F3862DE9C3?tenantId=9ce70869-60db-44fd-abe8-d2767077fc8f&fileType=xlsx&objectUrl=https%3A%2F%2Fcdc.sharepoint.com%2Fteams%2FUSDSatCDC%2FShared%20Documents%2FPRIME%20Data%20Input%2FNational%20COVID%20ELR%20_Data%20Elements%20and%20Gap%20Analysis_ForDistribution.xlsx&baseUrl=https%3A%2F%2Fcdc.sharepoint.com%2Fteams%2FUSDSatCDC&serviceName=teams&threadId=19:0d50dc5f21f44c439597f955074341e2@thread.skype&groupId=0a88b0f5-b203-4f1e-b67d-f9abe23ea76e

**Comment by aliciabeckett-gov** [comment]
The tag on the testing card needs to be updated from pending to complete if the questions are saved. @benwarfield-usds do you want to add that to this ticket or create a new one?

**Comment by benwarfield-usds** [comment]
That should be considered part of the "ask before submitting without data" item, IMO. I was aware of that missing piece, but it should be tracked on the punch list on the PR rather than in my head--will add it there.

**Comment by aliciabeckett-gov** [comment]
When you add someone to the queue and the AOE questions pop, if you say "add to queue" without completeing the quesitons there should not be the "You have incomplete data" modal.
Many orgs said they would want to do this, so we don't want to make it too difficult. It's also a modal on a modal...
If a person tries to submit a result without answering the. AOE questions then the popup "You have incomplete data" should keep showing up (the way it is working now. Keep that, it's good.)

**Comment by willusds** [comment]
@dmethvin-gov help with the alleyoop
