### ISSUE TITLE
Undo Button: Delete Test from Queue

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-central#58]
As a user managing the test queue, I want an undo button for deleting a test from the test queue, so that if I accidentally delete a test I can get it back.

-When a user deletes a test show a notification (toast) with an undo button for ~20 seconds
-If the user clicks the undo button, add the deleted test back into the queue
-Animate down the tests and add it back to the place where it was before

**Comment by hmyers-cms** [comment]
I don't think this is necessary. Instead we should build an "are you sure" confirmation when someone attempts to remove from queue. This was in the original design but never got coded.
![Screen Shot 2020-12-09 at 10 47 07 AM](https://user-images.githubusercontent.com/60664222/101652348-22a21c00-3a0c-11eb-969f-87fb8e656833.png)


The "undo" concept that I thought about (and maybe is where this is coming from?) was to be able to undo after you submit a result

**Comment by willusds** [comment]
Covered by other tickets
