### ISSUE TITLE
Submit and Save Test Results

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-central#59]
As a user administering tests, I want to be able to record the result of the test, so that my organization has a record of the test and the result, and the result can be sent to public health so that we are in compliance.

## Acceptance Criteria

Updated Nov 2, 2020
- [x] Allow the provider to select the test result.
- [x] Allow the user to submit the test result. (Neil: does prover and user mean the same thing?)
- [x] Allow the user to clear the test result (before submitting) (Neil: atm, this doesn't clear the test device, only the test result). Also, should it clear the AOE questionaire, or does that need its own "clear" button"?
~~- [ ] If the time of test questions were not completed, ask the user if they want to submit the result or answer the questions(will be a separate story)~~
- [x] Save result for the test (saves to localstorage + redux)
- [x] Remove the test from the testing queue
~~- [ ] animation around removing the test from the queue~~ (out-of-scope, captured in the styles issue)
~~- [ ] animation around notifications~~ (out-of-scope, captured in the styles issue)

UI here: https://heather574841.invisionapp.com/console/PDI-10-14-2020-HM-ckg9uf825007z01yg6dgr93w1/ckg9uf8v4006z010ig4c7baj8/play

**Comment by pete-gov** [comment]
Test result fields are in the test.schema.json file in this PR: https://github.com/CDCgov/prime-data-input-client/pull/7

**Comment by sharmaneil** [comment]
For the local prototype v1 demo-ed last week on demo day, the current state of this ticket is:
- [x]Allow the provider to select the test result.
- [x] Allow the user to submit the test result. (Neil: does prover and user mean the same thing?)
- [ ] Allow the user to clear the test result (before submitting) (Neil: this doesn't clear the test device, only the test result)
- [ ] If the time of test questions were not completed, ask the user if they want to submit the result or answer the questions(will be a separate story)
- [x] Save result for the test (saves to localstorage + redux)
- [ ] Remove the test from the testing queue
- [ ] animation around removing the test from the queue
- [ ] animation around notifications

**Comment by pete-gov** [comment]
Moving this back to To Do as it has outstanding features.

**Comment by pete-gov** [comment]
Fix for clearing device out for PR.

**Comment by pete-gov** [comment]
![clear-device](https://user-images.githubusercontent.com/51794651/98014015-1ac9d900-1dc9-11eb-838e-f106c7f0546a.gif)

Now with demo.
