### ISSUE TITLE
Export Test Results as CSV

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-central#60]
As a developer sending test results to Arizona, I want data exported as a CSV in the format I need, so that I can create a message for Arizona that will meet their spec.

**Acceptance Criteria**
-Export CSV of tests
-Include all data about the tests that corresponds to the spec needed by Arizona

This is test data being used to validate the format.

**Comment by pete-gov** [comment]
This feature depends on #90 .

**Comment by jimduff-usds** [comment]
FYI, at the moment, there is a definition of the csv fields expected, here:   https://github.com/CDCgov/prime-data-hub/blob/master/prime-router/metadata/schemas/PrimeDataInput/pdi-covid-19.schema
