### ISSUE TITLE
Create list of questions we need to answer to inform decisions about Stage 2 architecture

### ISSUE THREAD

**Issue by switzersc-usds** [CDCgov/prime-central#63]
As discussed in the engineering sync on 10/16, we need to better understand the constraints we have to work within before we can build to support Stage 2 (multiple devices, multiple users, single org). Then the next sprint we will work with product to get all these questions answered. 

Questions like do we need a three-way merge, do we need multi-tenant isolation, do we need server-side search, etc 

Acceptance Criteria
List of questions for Product/design, and urgency of answers needed (this sprint, future sprints, etc.)
Quick conversation with folks responsible for answering the questions (@aliciabeckett-gov @katiealoisi @hmyers-cms )to make sure they understand them

**Comment by pete-gov** [comment]
possibly off topic for this ticket but to track it [per Alicia's request here](https://usds.slack.com/archives/C019PRYMR0Q/p1603303098335200?thread_ts=1603297993.328700&cid=C019PRYMR0Q):

* would be handy at some point to have a specific list of devices and operating systems that people will expect to use on the pilot side (i.e. “iPad mini 3 / iOS 12”)

**Comment by willusds** [comment]
Covered by authentication #89 and cloud hosting #90, so closing!
