### ISSUE TITLE
We need analytics for SimpleReport

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-central#67]
We need monitoring of our application.

- [ ] Pick server side monitoring solution (likely new relic/splunk)
- [ ] Set up service side monitoring
- [ ] Pick client side monitoring solution (likely google analytics)
- [ ] Set up client side monitoring

**Describe the solution you'd like and the specific acceptance criteria to be completed**

**Describe alternatives you've considered**

**Additional context**

**Comment by willusds** [comment]
Broken out into other tickets and covered in Sprint 6
