### ISSUE TITLE
Patient result export for SimpleReport users

### ISSUE THREAD

**Issue by sharmaneil** [CDCgov/prime-central#7]
The MVP would output a CSV. Unanswered questions:
- do we need to have all the fields that were imported?
- can we change the values of any fields that were imported?
- what additional fields do we need to add? What is the format of these fields?

**Comment by timbest-cdc** [comment]
current export implemented in https://github.com/CDCgov/prime-data-input-client/blob/main/backend/src/main/java/gov/cdc/usds/simplereport/api/export/CSVExportController.java
