### ISSUE TITLE
Record and share next demo

### ISSUE THREAD

**Issue by switzersc-usds** [CDCgov/prime-central#72]
Decided on this action during the 10/21 community building working session, to support the need to share details about work with pilot partners and CDC. 

Maybe also edit this recording to make it good video content for our website.

**Comment by switzersc-usds** [comment]
We could even share this in our Google Group is we get it set up beforehand as per #73

**Comment by willusds** [comment]
Working on the deck here: https://docs.google.com/presentation/d/1g67pNTRbM4T5aWEmEgdcG35QwEmR4z-05H9D8YhOZmk/edit#slide=id.g8f09daa055_6_0

Please add things!

**Comment by willusds** [comment]
Completed and recorded the demo. Just getting clearance on where to post and email out from CDC.
