### ISSUE TITLE
Get approval for and set up Google Group (or other forum) for pilot partners

### ISSUE THREAD

**Issue by switzersc-usds** [CDCgov/prime-central#73]
Added "or other forum" in case we can't use Google Groups.

Maybe we should keep this as a closed group for now and decide if/when to open it up as part of our larger community roadmap.

**Comment by willusds** [comment]
We have approval! The CDC is setting this up for us and we'll have to use our CDC emails to join, but we have progress and should hopefully be able to start building it out this week, and send out our demo in the first message!

**Comment by willusds** [comment]
We're live with a closed group! [Instructions are here, holler at me with questions or approval needs](https://docs.google.com/document/d/1A1xxX_bgfh75mhIyXcspOQ2e_ResJ0oo5JOduE80gFQ/edit#).
