### ISSUE TITLE
test queue throws errors if there are no patients

### ISSUE THREAD

**Issue by pete-gov** [CDCgov/prime-central#79]
The current `main` branch is broken due to errors with the test queue:

```TypeError: can't convert undefined to object
./src/app/testQueue/testQueueSelectors.js/_getPatientIdsInTestQueue<
src/app/testQueue/testQueueSelectors.js:15

  12 | const _getPatientIdsInTestQueue = createSelector(
  13 |   _getPatientsInTestQueue,
  14 |   (patients) => {
> 15 |     return Object.keys(patients)
  16 |       .filter(
  17 |         (patientId) => patients[patientId] && patients[patientId].isInQueue
  18 |       )
```

```
TestQueue
src/app/testQueue/TestQueue.jsx:17

  14 | import QueueNotification from "./QueueNotification";
  15 | 
  16 | const TestQueue = () => {
> 17 |   const patients = useSelector(getDetailedPatientsInTestQueue);
  18 |   const notification = useSelector(getQueueNotification);
  19 |   const dispatch = useDispatch();
  20 | 
```

I'm guessing there just needs to be a check added to see if this exists and define it with a default or something if it doesn't?

**Comment by pete-gov** [comment]
Yeah, looks like there's basic support for an empty queue but it only works if patients exist and are defined. We need to add support for no patients.

**Comment by pete-gov** [comment]
Rather than handling this inside the TestQueue code, it seems like this should be handled at a higher level in the site - perhaps an initialization stage? Or perhaps just block access to any page except for the Add New Patient or Upload CSV functions until a patient has been created?

**Comment by pete-gov** [comment]
In the interim, I've changed the default to the `patients` route. Customizing the available routes based on whether or not patients is defined appears to be over my head. 🤷

**Comment by benwarfield-usds** [comment]
This seems like a situation that some unit tests might help with....

**Comment by pete-gov** [comment]
Adding a random datapoint, I wiped out my localstorage and patients is now auto-populating properly - but, we still need to keep this in mind because we can't auto populate patients for folks when we start testing.

**Comment by sharmaneil** [comment]
I am unable to recreate this; the app has changed a lot and the UI should be able to handle no patients. 

I agree with the points mentioned above:
- we should have unit tests in the selectors
- selectors should return `[ ]` if there are no values
- the UI needs to handle `[ ]`
- the app should be initialized with no values and it should still work

Design is lacking on what the desired UI/UX should be if there are no patients:
- should it redirect to the `Patients` page if there are no patients? I think the desired landing page in general is the TestQueue
- if there are no TestResults, should the test result table be empty, or should there be a more human-friendly message? ie: "There are no test results"
- same with if there are no Patients.

**Comment by pete-gov** [comment]
I think this will be address as part of #99 - will add a comment there to ensure it's on the radar and close this out.
