### ISSUE TITLE
Move client repo to CDCGov

### ISSUE THREAD

**Issue by sharmaneil** [CDCgov/prime-central#8]
Can someone with a CDC Teams account fill this out for prime data input client app? `prime-data-input-client` can be a v1 repo name. 

Step 1: Fill out this form
https://forms.office.com/Pages/ResponsePage.aspx?id=aQjnnNtg_USr6NJ2cHf8j44WSiOI6uNOvdWse4I-C2NUNk43NzMwODJTRzA4NFpCUk1RRU83RTFNVi4u

Step 2: move the code over from the usds org

Step 3: make sure everyone who would use the codebase has access, and then delete the usds repo.

**Comment by switzersc-usds** [comment]
I believe this is done!
