### ISSUE TITLE
Memory Leak - notifications

### ISSUE THREAD

**Issue by sharmaneil** [CDCgov/prime-central#80]
## Bug description

<img width="538" alt="Screen Shot 2020-10-26 at 10 38 54 PM" src="https://user-images.githubusercontent.com/35268641/97273899-23cb1100-17f1-11eb-9f1c-fc6e0f0ff7cf.png">

## How to recreate the issue:
- go to the queue
- add a patient to the queue. This triggers a notification
- immediately go to another tab before the notification expires. You can't unmount something that isn't rendered, hence the memory leak

## Root cause?

Neil skipped reading this section in the react hooks docs because it didn't seem important at the time.

## Priority - low

Non-blocking and non-user facing as far as I can tell, and the size of the leak is minimal to likely not be noticeable (this is a guess and has not been validated). 

Also, some of the logic around notifications need to change anyway (ie: how do we handle multiple simultaneous notifications), so the fix here might best be tackled whenever folks are on that part of the codebase. 

## Level of effort
Should be a pretty straightforward and quick fix with a little googling

**Comment by willusds** [comment]
Merged
