### ISSUE TITLE
Display Saved Test Results on the Results Screen

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-central#81]
**As an administrator at a nursing home I want to see past test results so that I can see what results have been sent to public health, if there are any new positive cases, and how long it has been since someone has tested, or has tested positive.**

## Acceptance Criteria

- [x] Results screen displays all test results
- [ ] Cannot see all test results for a single patient (this is possibly out of scope)
~~- [ ] styles~~ (out of scope, captured in a different ticket)  

Additional Context:
-If a staff member tests positive they do not need to be tested for another 90 days, and they need to wait 10 days to come back to work.
-CMS has issues guidance about frequency of testing based on a county's percent positivity rate:
_Under guidance CMS issued on August 26, 2020, nursing homes must test staff at a frequency of once monthly if the facility’s county positivity rate is less than five percent. Staff testing frequency increases to once weekly if the county positivity rate is between five and 10 percent. Finally, testing frequency increases to twice weekly if the county positivity rate exceeds 10 percent._
https://www.cms.gov/newsroom/press-releases/cms-updates-covid-19-testing-methodology-nursing-homes 

A clear and concise description of what the problem, user persona, and expected outcome.

**Describe the solution you'd like and the specific acceptance criteria to be completed**
-Display the recorded test results on the results page. This should show the user: who was tested, when they were tested (date and time), test result, if they had any symptoms, device that was used
-We need finalized fields to display for the results column and how that will look -Design/Product (For the prototype we can just dump out all the stuff we have in the DB_

**Describe alternatives you've considered**
We could just export the CSV, but that's a lot just to verify that the result was recorded (and unclear if that's easier than this)

**Additional context**
This is important for testing a prototype with users

**Comment by aliciabeckett-gov** [comment]
@sharmaneil - added this ticket based on our chat yesterday

**Comment by sharmaneil** [comment]
@aliciabeckett-gov 
https://github.com/CDCgov/prime-data-input-client/pull/22

**Comment by sharmaneil** [comment]
Not yet merged and deployed, so technically should remain open. Plus, it still needs QA + styling.

**Comment by aliciabeckett-gov** [comment]
@hmyers-cms @katiealoisi - if you have updated mocks of what the results page should look like based on our research can you attach it here.

**Comment by aliciabeckett-gov** [comment]
> Not yet merged and deployed, so technically should remain open. Plus, it still needs QA + styling.

Yeah... It took me a minute to figure out it was a pull request.

**Comment by pete-gov** [comment]
Looks like this is done now.
