### ISSUE TITLE
We need a landing page

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-central#82]
**Describe your feature request in this format: As a person who wants to record a test result I want to navigate to the app and login so that I can use the application**

**Describe the solution you'd like and the specific acceptance criteria to be completed**
-Entry point for logging into the product
-Authentication is a separate ticket
-Need a design
-Need a name
-Need an URL
-Need content for the website
-Need a logo and branding
-Terms of service

**Describe alternatives you've considered**

**Additional context**

**Comment by willusds** [comment]
Related to #99

**Comment by willusds** [comment]
Complete! Simplereport.cdc.gov!
