### ISSUE TITLE
To send a proper HL7 test result, device manufacture and device model is needed.

### ISSUE THREAD

**Issue by RickHawesUSDS** [CDCgov/prime-central#83]
**Background**
- Device ID is currently a field that is in the PDI's field list
- Device ID is used to represent an instrument instance 
- Accordingly, Device kind information is also needed
- Details found here https://confluence.hl7.org/display/OO/Proposed+HHS+ELR+Submission+Guidance+using+HL7+v2+Messages#ProposedHHSELRSubmissionGuidanceusingHL7v2Messages-DeviceIdentification

**Request**
PDI should also collect device manufacture and model. The manufactures and models should be restricted to those found on this mapping guide. https://www.cdc.gov/csels/dls/documents/livd_test_code_mapping/LIVD-SARS-CoV-2-2020-10-21.xlsx

**Comment by willusds** [comment]
For prototype, hard coding in this version. (Create a follow up issue for managing devices.)

**Comment by pete-gov** [comment]
New link: https://www.cdc.gov/csels/dls/sars-cov-2-livd-codes.html

Nothing is done with this yet and it will probably be handled manually through the pilot, but added it to the json config and renamed the display names for devices.

Merged:

```
export const initialDevicesState = {
  deviceId1: {
    displayName: "Abbott - ID NOW",
    deviceManufacturer: "Abbott",
    deviceModel: "ID NOW",
  },
  deviceId2: {
    displayName: "Abbott - BinaxNOW COVID-19 Ag Card",
    deviceManufacturer: "Abbott",
    deviceModel: "BinaxNOW COVID-19 Ag Card",
  },
};
```
