### ISSUE TITLE
Application needs a name 

### ISSUE THREAD

**Issue by benwarfield-usds** [CDCgov/prime-central#85]
**As a _human who converses with other humans_ I want to _have a specific name for the application_ so that _they can tell which application I am talking about._**

We are currently referring to this as "the app" or "the prototype" and that is neither very clear and unambiguous nor very good for marketing.

**The input prototype application should have a specific name, and we should refer to it by that name.**

**Alternatives**
* Data Buddy
* Dat App
* The App
* PRIME Input Test Application

** Acceptance Criteria **

- [x] Pick Name
- [ ] CDC Sign off @cygov 
- [x] Update application code to reflect the new name

**Comment by aliciabeckett-gov** [comment]
Other options that have been floated:
-Bolt
-Hermes

**Comment by willusds** [comment]
Public facing name, brand, run it by CDC, USDS and anyone else who needs sign off

**Comment by aliciabeckett-gov** [comment]
Some more ideas:

Reportease

FastReport

QuickReport

EasyReport

ReportNow

ReportEZ

EZReport

Recordease

Recordari

Reportare

Reportari

SimpleReport

SimpleReporter

SimpleResult

SimpleResults

ReportSimple

ReportDirect

Record and Report - RandR

FieldReport

FieldTestReport - FiTRe

**Comment by sharmaneil** [comment]
Of the options, I like `ReportSimple`, `ReportEasy`, `RecordEase`, (and similar permutations)

However, `Report` and `Record` can mean many things. For example, `SimpleReport` could be interpreted as:
- clean, easy to ingest/understand pdfs (referring to the noun `report`) 
- the ability to easily generate these pdfs
- the ability to easily send out notifications/updates (our intended definition)

Other word permutations to consider:
- ShareSimple
- SimpleNotify
- ResultInform,

**Comment by aliciabeckett-gov** [comment]
Hmmm good point. One consideration I had was thinking about going beyond testing. For example reporting symptoms, or other important data that may not be related to testing as the app expands (think big right?!)

I like ShareSimple, but wonder if it is too vague or just right?

**Comment by benwarfield-usds** [comment]
A lot of these seem too generic to me. If you were trying to figure out how to manage your university's test infrastructure, which of these names would you want to investigate more?

**Comment by switzersc-usds** [comment]
Ah crap, sorry I forgot to brainstorm this last week with folks. I was thinking the theme of messenger pigeons could be cool and apt, considering the quirky history of pigeon use for mail carrying as well as government use. For example, how about the name Tippler, a [breed of pigeon](https://en.wikipedia.org/wiki/Tippler) bred for endurance competitions? 

This would also lend itself to the Data Hub having a fun name like Dovecote, or DataCote ^.^

**Comment by hmyers-cms** [comment]
I just googled "tippler" to see a picture of the bird but google dictionary says it means "a habitual drinker of alcohol."
So we might not want to use that word. I like the carrier pigeon concept though!

**Comment by switzersc-usds** [comment]
Ha! That's so funny. My DuckDuckGo search only returns pigeon results in the top page.

**Comment by switzersc-usds** [comment]
Here's a list of pigeon breeds - there might be a gem in there! https://en.wikipedia.org/wiki/List_of_pigeon_breeds

**Comment by switzersc-usds** [comment]
Also, with government loving acronyms, I was trying to think of an acronym related to pigeons, but all I got to was PIDGE -- PRIME Important Data Goes Everywhere.  Bonus points for an acyonym within an acronym?

**Comment by katiealoisi** [comment]
Love the pigeon theme. Google tells me the term Pigeon is a French word coming from the Latin word, Pipio, which is short & sweet. Maybe it could lend itself to a creative acronym. Not convinced though, will keep brainstorming!

**Comment by willusds** [comment]
I got a pigeon guy, if we ever need one for a presentation or inspiration or something. He breeds and races them.

**Comment by cygov** [comment]
### What about (CDC/ HHS) SHARE?
**S -** simple
**H -** health
**A -** application
**R -** reporting
**E -** environment

> A lot of these seem too generic to me. If you were trying to figure out how to manage your university's test infrastructure, which of these names would you want to investigate more?

One thought, if our primary user will be outside traditional healthcare settings, agree we should make the name something that makes it clear what the use case is.

> Also, with government loving acronyms, I was trying to think of an acronym related to pigeons, but all I got to was PIDGE -- PRIME Important Data Goes Everywhere. Bonus points for an acyonym within an acronym?

**P -** prime
**I -** important
**D -** data
**G -** goes
**E -** everywhere
**O** - on 
**N -** networks

**Comment by aliciabeckett-gov** [comment]
I like Pipio! However, I do think there is a lot of value in having a name that helps the user understand the value of this application to them.

**Comment by aliciabeckett-gov** [comment]
@katiealoisi @hmyers-cms maybe we should test some of these with users, or ask them their ideas about naming?

**Comment by katiealoisi** [comment]
Sure, maybe at the end of the usability sessions we can present a few name options and ask which ones best communicate the purpose/value of the application. I'm not sure how valuable the feedback will be, but I don't think it will hurt. @hmyers-cms Let me know if you have any other ideas for how to test the name with users.

**Comment by aliciabeckett-gov** [comment]
Okay, based on a conversation with @katiealoisi and @cygov we have picked a name: **SimpleReport**

If you hate this name please speak now or live with it. Moving this ticket to review and if no one speaks up we'll run with it next week.

**Comment by aliciabeckett-gov** [comment]
Actually moving this back to in progress until we get CDC signoff

**Comment by cygov** [comment]
> Actually moving this back to in progress until we get CDC signoff

Brought it up to Alex today, shared our top choice SimpleReport as well as some of the other top contenders for CDC consideration (Pigeon, Pipio, EZReport, EasyReport).

**Comment by willusds** [comment]
It is **SimpleReport**!

**Comment by pete-gov** [comment]
We should probably snap up the simplereport domains before this name is widely shared if we're gonna stick with it... (especially since this discussion is public)
