### ISSUE TITLE
Input Application needs an OID

### ISSUE THREAD

**Issue by benwarfield-usds** [CDCgov/prime-central#86]
A requirement from @RickHawesUSDS from a reporting standpoint (he has more info), might be this: https://www.hl7.org/Oid/information.cfm

**Comment by willusds** [comment]
@nickrobison-usds has an OID ! and might be able to help

**Comment by nickrobison-usds** [comment]
Here's the link to my OID: http://oid-info.com/get/1.3.6.1.4.1.54629
CDC also has its own as well: http://www.oid-info.com/get/2.16.840.1.114222

@RickHawesUSDS do you know if these IDs need to be issued by HL7, or can we use whatever, as long as it's consistent?

**Comment by RickHawesUSDS** [comment]
I've put in a request to the CDC PHIN program for a CDC OID.

**Comment by aliciabeckett-gov** [comment]
This is completed:

CDC PRIME - Atlanta, Georgia (Dekalb)
OID: 2.16.840.1.114222.4.1.237821
