### ISSUE TITLE
Find a cloud host for the Data Input App and Data Hub Router.

### ISSUE THREAD

**Issue by RickHawesUSDS** [CDCgov/prime-central#88]
**Background**
Both the Data Input App and Data Router need a cloud host for their MVP. 

**Acceptance Criteria**
- Must be HIPPA compliant and able to ATO
- Agreement by the CDC
- Agreement with the new hosting provider
- Documentation of implications for authentication, and other issues
- Communication of decisions

**Comment by RickHawesUSDS** [comment]
Have a direction and two possible options that I can share privately.

**Comment by aliciabeckett-gov** [comment]
This seems to be the same as #10

**Comment by aliciabeckett-gov** [comment]
@RickHawesUSDS is this complete?
