### ISSUE TITLE
Find an authentication service

### ISSUE THREAD

**Issue by sharmaneil** [CDCgov/prime-central#9]
After prototype is up, then figure out authentication
Need to know user need and data out of it

AC / Output needs:
- Mapping out process and needs (does it need to be user, api based), costs, security

**Comment by aliciabeckett-gov** [comment]
@willusds is investigating possible options with Login.gov, HHS Okta, and others

**Comment by timbest-cdc** [comment]
we are using hhs-prime.okta.com
