### ISSUE TITLE
Usability testing with the facility in AZ

### ISSUE THREAD

**Issue by willusds** [CDCgov/prime-central#95]
Do usability testing with long term care facilities in Pima County.

Acceptance Criteria
- [x] Schedule at least 3 usability testing sessions at pilot sites
- [x] Complete at least 3 usability testing sessions
- [x] Do testing sessions with both people who would do the testing, and administrators who are responsible for reporting
- [x] Identify actionable recommendations to improve design
- [x] Share with the team in slack so folks can gawk

**Comment by katiealoisi** [comment]
**Conduct usability testing of the coded prototype with assisted living facilities in Pima County**

* Identify at least one assisted living facility in Pima County to serve as our first pilot site
* Schedule at least 3 usability testing sessions at pilot site
* Identify actionable recommendations to improve design

**Comment by katiealoisi** [comment]
@aliciabeckett-gov Would you like me to contact Kat to get a short list of assisted living facilities to meet with, or do you already have the ball rolling? Happy to help if it's not already underway.

**Comment by aliciabeckett-gov** [comment]
I've got it rolling, but thanks for asking! I'll add you to the thread.

**Comment by aliciabeckett-gov** [comment]
@katiealoisi just talked to Kat. Next steps here:

1. Set up usability testing with the SNF facilities we've already talked to (this is the fastest path to usability testing)
2. Kat is reaching out to Assisted Living Facilities to see if they will pilot or do usability testing. Once she gets them to agree she will connect us to them.

**Comment by aliciabeckett-gov** [comment]
I'm going to break "Identify at least one assisted living facility in Pima County to serve as our first pilot site" as a separate ticket.

**Comment by katiealoisi** [comment]
Just heard from Kat - Via Elegante (an assisted living facility) has agreed to serve as our first pilot site! I can get the ball rolling with them to set up usability testing. We also have volunteers from Devon Gables and Santa Rita (SNFs in Pima County) but they have all seen the app before. I think it will still be useful, but we need to be aware that the app and how it works has already been demoed to them.

**Comment by willusds** [comment]
@hmyers-cms @katiealoisi is this ready to close? I think we have many more than 3 tests done!

**Comment by willusds** [comment]
Done!
