### ISSUE TITLE
General style cleanup

### ISSUE THREAD

**Issue by willusds** [CDCgov/prime-central#96]
Give the app some fit and finish polish. This is front end styling work, not any functionality changes.

**Acceptance Criteria**
- [x] The app looks polished and professional. It's ready for PRIME time!

**Comment by pete-gov** [comment]
Tracking this for a bugfix:
- [ ] menu nav options disappear when the interface transitions to a smaller viewport

Normal Size:
<img width="1027" alt="Screen Shot 2020-11-06 at 11 26 07 AM" src="https://user-images.githubusercontent.com/51794651/98390182-05e88200-2023-11eb-8059-81ca3952dbd0.png">

Smaller:
<img width="984" alt="Screen Shot 2020-11-06 at 11 26 15 AM" src="https://user-images.githubusercontent.com/51794651/98390209-0c76f980-2023-11eb-943d-2f4da24d1314.png">

**Comment by aliciabeckett-gov** [comment]
Done for now
