### ISSUE TITLE
Access & details for cloud environment

### ISSUE THREAD

**Issue by willusds** [CDCgov/prime-central#97]
**User story**
We need access to environments and accounts so that we can deploy our app in our real environment for the pilot.

**Acceptance Criteria**
Accounts, details, all the things needed for setting up a sandbox and beyond!

- [ ] Sandbox environment is available to our team
- [ ] App is deployed and running in the sandbox environment
- [ ] Any security considerations or approvals (create separate ticket)

**Comment by aliciabeckett-gov** [comment]
Suggest we leverage Nick Robinson to help with this.

**Comment by pete-gov** [comment]
I got an e-mail about this so it looks like it's in progress.

**Comment by pete-gov** [comment]
https://usds.slack.com/archives/C01B2LH9B3P/p1604902701160000 Going a different route but looks like Rick did the needful, moving this to Review.
