### ISSUE TITLE
Style CSV Upload Features

### ISSUE THREAD

**Issue by pete-gov** [CDCgov/prime-central#98]
_As an administrator at a testing site, I want to upload patients to the app and see if they are successfully added, so that I don't have to add them one at a time and I can begin to test the people._

This is a styling followup to the following issue: https://github.com/CDCgov/prime-central/issues/54

**Upload CSV Styling:**

- [x] style the upload CSV portion
- [x] style rows that will be added
- [ ] style rows that will be updated
- [ ] style rows that are duplicates
- [x] style rows that have errors and won't be added
- [ ] style confirmation boxes
- [ ] style modal
- [x] User is able to see which rows will be added and which rows will not be added
- [ ] If the upload fails the user gets an error message telling them what happened
- [ ] Offer some sort of design/summary for what happened, "It worked, go look at the people tab!"

UI: https://heather574841.invisionapp.com/console/PDI-10-14-2020-HM-ckg9uf825007z01yg6dgr93w1/ckg9uf8v4006t010i7pzc7ilh/play

**Comment by pete-gov** [comment]
Neil has been working on this so moving to in progress for now: https://github.com/CDCgov/prime-data-input-client/pull/55

**Comment by timbest-cdc** [comment]
patient uploading is currently an engineer task and was remove from the UI
